<a href="https://colab.research.google.com/github/syifnrl/PA_Orbit/blob/main/Chatbot_TFIDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import nltk
import random
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
import pandas as pd
import random

import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import warnings
warnings.filterwarnings("ignore")

In [5]:
data_objek = pd.read_csv('/content/Dataset_Objek_Museum.csv', delimiter=';')
df_objek = pd.DataFrame(data_objek)
df_objek

Apa tujuan berdirinya museum Asia – Afrika  \
0   Memperingati peristiwa Konferesi Asia – Afrika...   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5                                                 NaN   
6                                                 NaN   
7                                                 NaN   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14                                                NaN   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21                                                NaN   
22                                                NaN   
23                                                NaN   
24                                                NaN   
25                                                NaN   
26                                                NaN   
27                                                NaN   
28                                                NaN   

                                       Gedung Merdeka  \
0   Gedung Merdeka dibangun pada tahun 1895 dengan...   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5                                                 NaN   
6                                                 NaN   
7                                                 NaN   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14                                                NaN   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21                                                NaN   
22                                                NaN   
23                                                NaN   
24                                                NaN   
25                                                NaN   
26                                                NaN   
27                                                NaN   
28                                                NaN   

   Kejadian yang melatar belakangi Konferensi Asia – Afrika  \
0   Perang Dingin, Perang Dunia II, Sistem Aparthe...         
1                                                 NaN         
2                                                 NaN         
3                                                 NaN         
4                                                 NaN         
5                                                 NaN         
6                                                 NaN         
7                                                 NaN         
8                     

In [6]:
len(df_objek.columns)

17

In [37]:
nltk.download('punkt')
sent_token = []

for col in df_objek.columns:
  get_token = sent_tokenize(col)
  sent_token += get_token
sent_token

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Apa tujuan berdirinya museum Asia – Afrika',
 'Gedung Merdeka',
 'Kejadian yang melatar belakangi Konferensi Asia – Afrika',
 'Perang Dunia II',
 'Perang Dingin',
 'Apartheid',
 'Kolonialisme',
 'Peristiwa sebelum Konferensi Asia Afrika (KAA)',
 'Pertemuan Tugu',
 'Konferensi Kolombo',
 'Pernyataan bersama menteri negara ASEAN terhadap masalah dunia pasca Perang Dunia II',
 'Konferensi Bogor',
 'Delegasi Partisipan Konferensi Asia Afrika',
 'Tokoh Konferensi Asia Afrika',
 'Dampak Konferensi Asia Afrika',
 'Gerakan Non Blok',
 'Komite Konferensi Asia – Afrika']

In [38]:
df_objek[sent_token[10]].iloc[0] is None

False

In [39]:
word_token = []

for col in df_objek.columns:
  get_token = word_tokenize(col)
  word_token += get_token
word_token

['Apa',
 'tujuan',
 'berdirinya',
 'museum',
 'Asia',
 '–',
 'Afrika',
 'Gedung',
 'Merdeka',
 'Kejadian',
 'yang',
 'melatar',
 'belakangi',
 'Konferensi',
 'Asia',
 '–',
 'Afrika',
 'Perang',
 'Dunia',
 'II',
 'Perang',
 'Dingin',
 'Apartheid',
 'Kolonialisme',
 'Peristiwa',
 'sebelum',
 'Konferensi',
 'Asia',
 'Afrika',
 '(',
 'KAA',
 ')',
 'Pertemuan',
 'Tugu',
 'Konferensi',
 'Kolombo',
 'Pernyataan',
 'bersama',
 'menteri',
 'negara',
 'ASEAN',
 'terhadap',
 'masalah',
 'dunia',
 'pasca',
 'Perang',
 'Dunia',
 'II',
 'Konferensi',
 'Bogor',
 'Delegasi',
 'Partisipan',
 'Konferensi',
 'Asia',
 'Afrika',
 'Tokoh',
 'Konferensi',
 'Asia',
 'Afrika',
 'Dampak',
 'Konferensi',
 'Asia',
 'Afrika',
 'Gerakan',
 'Non',
 'Blok',
 'Komite',
 'Konferensi',
 'Asia',
 '–',
 'Afrika']

In [40]:
stopword = nltk.download('stopwords')
stopwords_ind = stopwords.words('indonesian')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [41]:
#Uji TFIDF
test = "perang dingin"
sent_token.append(test)
vectorizer = TfidfVectorizer(ngram_range=(1,1), stop_words=stopwords_ind)
model = vectorizer.fit_transform(sent_token)
model_toarray = model.toarray()
model_toarray


array([[0.29991353, 0.        , 0.        , 0.29991353, 0.        ,
        0.52284598, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.52284598,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.52284598],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
      

In [42]:
flat = []
similarity = cosine_similarity(model[-1], model)
flat = similarity.flatten()[:-1]
flat

array([0.        , 0.        , 0.        , 0.31831955, 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.14900809, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [43]:
index = flat.argsort()
index

array([ 0, 14, 13, 12, 11,  9, 15,  8,  6,  5,  2,  1,  7, 16, 10,  3,  4])

In [44]:
print(sent_token[index[-1]])
print(sent_token[index[-2]])

Perang Dingin
Perang Dunia II


In [45]:
sent_token.remove(sent_token[-1])
sent_token

['Apa tujuan berdirinya museum Asia – Afrika',
 'Gedung Merdeka',
 'Kejadian yang melatar belakangi Konferensi Asia – Afrika',
 'Perang Dunia II',
 'Perang Dingin',
 'Apartheid',
 'Kolonialisme',
 'Peristiwa sebelum Konferensi Asia Afrika (KAA)',
 'Pertemuan Tugu',
 'Konferensi Kolombo',
 'Pernyataan bersama menteri negara ASEAN terhadap masalah dunia pasca Perang Dunia II',
 'Konferensi Bogor',
 'Delegasi Partisipan Konferensi Asia Afrika',
 'Tokoh Konferensi Asia Afrika',
 'Dampak Konferensi Asia Afrika',
 'Gerakan Non Blok',
 'Komite Konferensi Asia – Afrika']

In [11]:
def response(user_response):
  chatbot_response= ''
  sent_token.append(user_response)
  vec = TfidfVectorizer(stop_words=stopwords_ind)
  tfidf = vec.fit_transform(sent_token)
  vals = cosine_similarity(tfidf[-1], tfidf)
  flat = vals.flatten()[:-1]
  idx = flat.argmax()

  if(flat.max() == 0):
    print("Maaf kami tidak mengerti pertanyaan anda!")
  else:
    idx = flat.argmax()
    for i in range (0, len(df_objek[sent_token[idx]])):
      if (df_objek.at[i, sent_token[idx]]) != "":
        print(df_objek[sent_token[idx]].iloc[i])
      else:
        break
    sent_token.remove(sent_token[-1])

In [12]:
user_intro = ['hai', 'halo', 'tes', 'pagi', 'siang', 'malam', 'hi']
bot_intro = ['Halo', 'Selamat Datang', 'Hai!', 'Senang berbicara dengan Anda!']

def greetings(text):
  for word in text.split():
    if word.lower() in user_intro:
      return random.choice(bot_intro)

In [13]:
user_end = ['bye', 'exit', 'selesai', 'dadah', 'selamat tinggal']
bot_end = "Terima kasih telah menggunakan chatbot ini, selamat tinggal!"

def exit_bot(text):
  for word in text.split():
    if word.lower() in user_end:
      return bot_end

In [14]:
flag = True

while flag:
  user_input = input()
  user_input = user_input.lower()
  if exit_bot(user_input) is not None:
    print(exit_bot(user_input))
    flag = False
  else:
    if greetings(user_input) is not None:
      print(greetings(user_input))
    else:
      response(user_input)


delegasi
Sardar Mohammad Naim (Menteri Luar Negeri Afghanistan) 
U Nu (Perdana Menteri Birma) 
     Prince Norodom Sihanouk (Mantan Raja Kamboja) 
     Sir John Kotelawala (Perdana Menteri Ceylon) 
     Chou En Lai (Perdana Menteri Republik Rakyat Tiongkok) 
     Gamal Abdel Nasser (Perdana Menteri Mesir) 
     Yilma Deressa (Ketua Delegasi Ethiopia di PBB) 
     Kojo Botsio (Menteri Negara Pantai Emas) 
     Pandit Jawaharlal Nehru (Perdana Menteri Indi) 
    Ali Sastroamidjojo (Perdana Menteri Indonesia) 
    Ali Amini (Menteri Keuangan Iran) 
    Mohammad Fadhil El Jamali (Anggota Parlemen Irak) 
    Tatsunosuke Takasaki (Menteri Negara Jepang) 
    Hazza Al Majali (Perdana Menteri Yordania) 
    Katay Don Sasorith (Perdana Menteri Laos) 
    Sami Bek Solh (Perdana Menteri Libanon) 
    Momolu Dukuly (Pejabat Sekretaris Negara Liberia)
    Mahmoud Bey Muntasser (Duta Besar Libya di London) 
    Sovag Jung Thapa (Menteri Luar Negeri Nepal) 
    Mohammed Ali (Perdana Menteri Pakistan)

In [15]:
sent_token

['Apa tujuan berdirinya museum Asia – Afrika',
 'Gedung Merdeka',
 'Kejadian yang melatar belakangi Konferensi Asia – Afrika',
 'Perang Dunia II',
 'Perang Dingin',
 'Apartheid',
 'Kolonialisme',
 'Peristiwa sebelum Konferensi Asia Afrika (KAA)',
 'Pertemuan Tugu',
 'Konferensi Kolombo',
 'Pernyataan bersama menteri negara ASEAN terhadap masalah dunia pasca Perang Dunia II',
 'Konferensi Bogor',
 'Delegasi Partisipan Konferensi Asia Afrika',
 'Tokoh Konferensi Asia Afrika',
 'Dampak Konferensi Asia Afrika',
 'Gerakan Non Blok',
 'Komite Konferensi Asia – Afrika']